// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonInCharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TourType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.HasIndex("Status", "IsDeleted");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("Domain.Entities.RequestDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingRequestId");

                    b.ToTable("RequestDetails");
                });

            modelBuilder.Entity("Domain.Entities.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.HasIndex("City", "IsActive", "IsDeleted");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-000000000000"),
                            City = "Hà Nội",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trải nghiệm văn hóa, ẩm thực và các địa danh nổi tiếng tại Hà Nội. Phù hợp cho gia đình và khách lẻ.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour du lịch khám phá Hà Nội 2 ngày 1 đêm",
                            Price = 1500000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-000000000001"),
                            City = "Đà Nẵng",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trải nghiệm văn hóa, ẩm thực và các địa danh nổi tiếng tại Đà Nẵng. Phù hợp cho gia đình và khách lẻ.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour du lịch khám phá Đà Nẵng 3 ngày 2 đêm",
                            Price = 1700000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-000000000002"),
                            City = "Hồ Chí Minh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trải nghiệm văn hóa, ẩm thực và các địa danh nổi tiếng tại Hồ Chí Minh. Phù hợp cho gia đình và khách lẻ.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour du lịch khám phá Hồ Chí Minh 4 ngày 3 đêm",
                            Price = 1900000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-000000000003"),
                            City = "Đà Lạt",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trải nghiệm văn hóa, ẩm thực và các địa danh nổi tiếng tại Đà Lạt. Phù hợp cho gia đình và khách lẻ.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour du lịch khám phá Đà Lạt 5 ngày 4 đêm",
                            Price = 2100000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-000000000004"),
                            City = "Nha Trang",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Trải nghiệm văn hóa, ẩm thực và các địa danh nổi tiếng tại Nha Trang. Phù hợp cho gia đình và khách lẻ.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tour du lịch khám phá Nha Trang 6 ngày 5 đêm",
                            Price = 2300000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Domain.Entities.RequestDetail", b =>
                {
                    b.HasOne("Domain.Entities.BookingRequest", "BookingRequest")
                        .WithMany("Details")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingRequest");
                });

            modelBuilder.Entity("Domain.Entities.BookingRequest", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
